{{- if .Values.autoscaling.enabled }}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "sogo6.fullname" . }}-server
  labels: {{ include "sogo6.labels" . | nindent 4 }}
    component: server
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "sogo6.fullname" . }}-server
  minReplicas: {{ .Values.autoscaling.server.minReplicas }}
  maxReplicas: {{ .Values.autoscaling.server.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.autoscaling.server.targetCPU }}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "sogo6.fullname" . }}-ui
  labels: {{ include "sogo6.labels" . | nindent 4 }}
    component: ui
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "sogo6.fullname" . }}-ui
  minReplicas: {{ .Values.autoscaling.ui.minReplicas }}
  maxReplicas: {{ .Values.autoscaling.ui.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.autoscaling.ui.targetCPU }}
{{- end }}
