apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sogo6.secret" . }}
  labels: {{ include "sogo6.labels" . | nindent 4 }}
type: Opaque
stringData:
  SOGO_P_DB_PASS: "{{ .Values.secrets.postgresPassword }}"
  SOGO_P_LDAP_BIND_PASSWORD: "{{ .Values.secrets.ldapAdminPassword }}"
  SCIM_BEARER_TOKEN: "{{ .Values.secrets.scimBearerToken }}"
  INTERCOM_SHARED_SECRET: "{{ .Values.secrets.intercomSharedSecret }}"
  SOGO_AES_ENC_KEY: "{{ .Values.secrets.aesEncKey }}"
  SOGO_P_VOUCHER_SECRET: "{{ .Values.secrets.intercomSharedSecret }}"
  postgres-password: "{{ .Values.secrets.postgresPassword }}"
  ldap-admin-password: "{{ .Values.secrets.ldapAdminPassword }}"
