apiVersion: v1
kind: Service
metadata:
  name: {{ include "sogo6.fullname" . }}-ui
  labels:
    {{- include "sogo6.labels" . | nindent 4 }}
    component: ui
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
  selector:
    {{- include "sogo6.selectorLabels" . | nindent 4 }}
    component: ui
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "sogo6.fullname" . }}-server
  labels:
    {{- include "sogo6.labels" . | nindent 4 }}
    component: server
spec:
  type: ClusterIP
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
  selector:
    {{- include "sogo6.selectorLabels" . | nindent 4 }}
    component: server
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "sogo6.fullname" . }}-stalwart
  labels:
    {{- include "sogo6.labels" . | nindent 4 }}
    component: stalwart
spec:
  type: ClusterIP
  ports:
    - name: smtp
      port: 25
      targetPort: 25
    - name: smtps
      port: 465
      targetPort: 465
    - name: submission
      port: 587
      targetPort: 587
    - name: imap
      port: 143
      targetPort: 143
    - name: imaps
      port: 993
      targetPort: 993
  selector:
    {{- include "sogo6.selectorLabels" . | nindent 4 }}
    component: stalwart
